---
title: "CBASS Demo"
author: "Yulia Iakovleva"
format: html
editor: visual
---

## About CBASS

CBASS allows you to process CBASS data. To learn more about CBASS see <https://onlinelibrary.wiley.com/doi/10.1111/gcb.15148>.

## Install CBASS

```{r install-cbass}
if(!require(devtools)){
    install.packages("devtools")
}

devtools::install_github()
```

## Load Packages

```{r library-packages}
library(CBASS)
```

## Preprocess and Validate Data

Load the provided example data set:

```{r load-data}
data("cbass_dataset")
head(cbass_dataset)
```

Make your data tidy and validate.

```{r process-and-validate-cbass-dataset}
cbass_dataset <- preprocess_dataset(cbass_dataset)
validate_cbass_dataset(cbass_dataset)
```

## Explore ED50

First you need to decide which grouping property you want to use. For example, I want to use `Site` , `Species`, `Genotype`:

```{r fititng-dose-responce-models}
grouping_properties <- c("Site", "Species", "Genotype")
drm_formula <- "PAM ~ Temperature"
models <- fit_drms(cbass_dataset, grouping_properties, drm_formula)
```
